### ISSUE TITLE
Operation with array.

### ISSUE THREAD

**Issue by wuhengzhi** [Zaseth/bytearray-node#1]
For as3, the first element will be modified with following code:
```
 var byteArray = new ByteArray();
 byteArray.writeByte(55);
 byteArray[0] = 50;
```
How to reach it with bytearray-node?
Thanks

**Comment by Zaseth** [comment]
Hello.

Did this work for you? If you're not going to reply in 2 days then I'm assuming it's working and I'll close this.

**Comment by Zaseth** [comment]
Because the value is way too big.

**Comment by wuhengzhi** [comment]
Yes, so I give up to emulate actionscript's ByteArray.
Thanks.

**Comment by Zaseth** [comment]
It's not the library's issue. You're writing a greater number than int32 can handle. It's your own problem.

**Comment by wuhengzhi** [comment]
Yes, I know the number is overflow.
I wanna transfer the actionscript code to javascript, but the numbers are got by logical operation, I can't modify them.

**Comment by Zaseth** [comment]
You're not supposed to do this in the beginning so I don't see why you'd want this to be the same as Actionscript. This is not valid and is just a way Node.js handles an overflow.
