### ISSUE TITLE
ByteArray image

### ISSUE THREAD

**Issue by fearcbz-ajdot** [Zaseth/bytearray-node#10]
Hello, i have big problem to convert an image to byte array, is this possible with this node? And if yes how to do that?

**Comment by Zaseth** [comment]
You can read an image using `fs.readFile` and then wrapping the `data` param into a ByteArray.

```js
const { readFile } = require('fs')

readFile('image.jpg', (err, data) => {
  if (err) throw err
  const ba = new ByteArray(data)
})
```

**Comment by fearcbz-ajdot** [comment]
Thank you!

**Comment by Zaseth** [comment]
If you have any more questions you can add me on Discord: Zaseth#3300
