### ISSUE TITLE
AMF3 marker 11

### ISSUE THREAD

**Issue by bobaoapae** [Zaseth/bytearray-node#11]
AMF with this marker is not supported [https://prnt.sc/vou0kl](https://prnt.sc/vou0kl)

**Comment by bobaoapae** [comment]
`(node:2340) UnhandledPromiseRejectionWarning: TypeError: Unknown or unsupported marker found: '11'.
    at Deserializer.deserialize (C:\Users\jvbor\WebstormProjects\morn-ui-tool\node_modules\amf3-ts\dist\core\deserializer.js:58:28)
    at Deserializer.deserializeObject (C:\Users\jvbor\WebstormProjects\morn-ui-tool\node_modules\amf3-ts\dist\core\deserializer.js:210:35)
    at Deserializer.deserialize (C:\Users\jvbor\WebstormProjects\morn-ui-tool\node_modules\amf3-ts\dist\core\deserializer.js:51:56)
    at Function.parse (C:\Users\jvbor\WebstormProjects\morn-ui-tool\node_modules\amf3-ts\dist\AMF3.js:96:12)
    at ByteArray.readObject (C:\Users\jvbor\WebstormProjects\morn-ui-tool\node_modules\bytearray-node\src\index.js:398:14)
    at C:\Users\jvbor\WebstormProjects\morn-ui-tool\index.js:14:28`

**Comment by Zaseth** [comment]
Thank you for reporting this to me, I pretty much forgot about this one. At the moment I'm very busy with other things and AMF isn't my first priority, but I'll definitely add this to my todos. Until then, perhaps you could create a PR if you wish to do so.

**Comment by ROBERT-MCDOWELL** [comment]
it would be very cool as Flash is ending end of December and also it will be +1 for JS/Wasm Flash emulator like Ruffle or Waflash.

**Comment by Zaseth** [comment]
At this very moment I'm employed as a single-working backend developer in a big project shifting from Flash to HTML5, so I don't have a lot of free time for this. Some big work has to be done to implement this marker as both AMF implementations aren't connected in any manner, and never will. I need to create one general library that includes AMF0 and AMF3, making it AMF-TS. This is something that I was going to do anyway.

I totally understand that preserving AMF is crucial for emulating certain pieces of the internet as we know it. My aim has always been that goal, and I achieved it as my implementations are fully identical and supportive to the real deal. It's just that for now, I don't have the time for it as I'm just a young chap following school and a huge hobby project.

I'll try to plan it into my schedule anytime soon though!

**Comment by Zaseth** [comment]
@bobaoapae Could you please share the data that you're trying to deserialize? I just remembered that the AVM marker is only used with remoting, which is something that is not implemented.

**Comment by bobaoapae** [comment]
@Zaseth link to download my file [https://mega.nz/file/D9gmXAgK#J2jAXj8S1xRQqUsJHtRx4dTiP8unN6n5xSzdUIng0q8](https://mega.nz/file/D9gmXAgK#J2jAXj8S1xRQqUsJHtRx4dTiP8unN6n5xSzdUIng0q8)

**Comment by Zaseth** [comment]
Thanks. Xml is not supported in the library.
