### ISSUE TITLE
How to convert the following python code to js code with bytearray-node?

### ISSUE THREAD

**Issue by iamweilee** [Zaseth/bytearray-node#12]
Hi Daan, how to convert the following python code to js code with bytearray-node?
I hope to get some guidance from you.
Thanks!

```
# python code
pkg = bytearray.fromhex(u"0c 0c 18 6c 00 01 08 00 08 00 4e 04")
market_pkg = struct.pack("<H", 0)
pkg.extend(market_pkg)
pkg.extend(b'\x75\xc7\x33\x01')
```

**Comment by Zaseth** [comment]
Hi @iamweilee 

Here's the code:

```js
const ByteArray = require('bytearray-node')
const { Endian } = require('bytearray-node/enums')

const pkg = new ByteArray(Buffer.from('0c0c186c0001080008004e04', 'hex'))
const extend = new ByteArray(Buffer.from('75c73301', 'hex'))

pkg.position = pkg.bytesAvailable
pkg.endian = Endian.LITTLE_ENDIAN // <

pkg.writeShort(0) // H, writes market_pkg
pkg.writeBytes(extend)
```

Hope I helped.

**Comment by iamweilee** [comment]
Thanks @Zaseth ，I tried the code from you. And there is an error threw from the module 'bytearray-node'.
![image](https://user-images.githubusercontent.com/1096160/108578294-110ab800-735d-11eb-8361-06922bfe805d.png)

**Comment by Zaseth** [comment]
You need to update your Node because my libraries are written in the most updated version of Ecmascript. Grabbing the latest LTS release should do it. I cannot help you if you're not able to update, maybe try a package that manages multiple Node versions.

**Comment by iamweilee** [comment]
> You need to update your Node and build tools because my libraries are written in the most updated version of Ecmascript. Grabbing the latest LTS release should do it. I cannot help you if you're not able to update, maybe try a package that manages multiple Node versions.

It's a pity that my project can only rely on Node 8. Thanks a lot.
