### ISSUE TITLE
I encrypted an array, but it was an object that was decrypted.

### ISSUE THREAD

**Issue by Ackerc** [Zaseth/bytearray-node#2]
let B_ = new ByteArray();
B_.writeObject(new Array(1, 2, 3));
new ByteArray(B_.buffer).readObject()  //---->{ '0': 1, '1': 2, '2': 3 }

**Comment by AckerC** [comment]
at AMF3.js :26
for (const x in array) //  x  must be a string. 
      if (x !== test) { //must be false ,I don't know what's the use of this.
        return false
      }

**Comment by Ackerc** [comment]
@Zaseth

**Comment by Zaseth** [comment]
Try to use [1, 2, 3] and use B_.readObject

**Comment by Ackerc** [comment]
@Zaseth Thanks!

**Comment by Zaseth** [comment]
Hello,

Do you mind adding me on Discord? I'm a busy student from Monday to Friday and I can't look at Github all day.

**Comment by Zaseth** [comment]
Closing this as it's fixed. Discord: Zaseth#7550
