### ISSUE TITLE
Convert unsigned byte to signed byte in writeByte

### ISSUE THREAD

**Issue by Yovach** [Zaseth/bytearray-node#4]
Hello !
In my opinion, it might be nice to make sure that bytes above 127 are replaced directly in the code.

For example, when you pass in parameter 192, it writes -64. It could avoid errors and automatically write the right byte.

If you are interested, I made a function that overrides the writeByte of the module 

``    writeByte(value) {
        if (value > 127) value -= 256;
        super.writeByte(value);
    }
``

**Comment by Zaseth** [comment]
Hello.

That's why writeUnsignedByte is available. Buffer will also throw an overflow error so it's all fine.

**Comment by Yovach** [comment]
Hello !
In the Flash ByteArray, bytes greater than 127 are converted automatically (in the writeByte function). It's not mandatory but it could be fun:)

Thank you for your answer!

**Comment by Zaseth** [comment]
Flash doesn't have writeUnsignedByte function, Node.js does. I have no idea why Adobe did it like this.

**Comment by Yovach** [comment]
Oh, I didn't notice there wasn't this feature in the code!
You just opened my eyes xd
Thank you!

**Comment by Zaseth** [comment]
If you have any other questions, feel free to open this issue again.
