### ISSUE TITLE
node-amf package

### ISSUE THREAD

**Issue by iongion** [Zaseth/bytearray-node#5]
Hi,

Are you still maintaining `node-amf` ?
The npm package shows broken links to one of your repos, check this https://www.npmjs.com/package/node-amf

Should bytearray-node considered successor of node-amf ?
I have also seen dependency on zlib and iconv, do you think this project can be used in the browser too ?

From the AMF0 and AMF3 spec, do you have a list of what is covered and what is not ?

Awesome project, congrats! Very useful for efficient web-socket servers in conjunction with **ws** project

**Comment by Aethusx** [comment]
Hey @Zaseth, i need to contact you but your discord tag is invalid. Add me, Aethus#4466.

**Comment by Zaseth** [comment]
@Aethusx added
