### ISSUE TITLE
Class implementing IExternalizable cannot call ByteArray.readObject inside readExternal

### ISSUE THREAD

**Issue by Flynnn** [Zaseth/bytearray-node#6]
Doing so causes a new instance of AMF3 to be created; An instance which does not have access to the traits/objects/strings reference tables of the original AMF3 instance spawning the the IExternalizable instance.

Suggested fix: Modify ByteArray.readObject to create an instance of AMF3 only once, and refer back to this instance on subsequent calls to readObject.

**Comment by Zaseth** [comment]
Could you please share example code that creates this error?

**Comment by Flynnn** [comment]
Sure. I'm working with some legacy AMF data right now, so recreation is just outside of my grasp, and this particular bug cannot be created within your framework since the corresponding writeObject is impossible inside writeExternal, but give me a week or two and I'll likely have some simple raw AMF data and an example for you.

I'm not 100% certain whether AS3's ByteArray technically supports this either, but the data I am working with would seem to suggest that it does.

**Comment by Zaseth** [comment]
Is your question related to bottom code:

```js
const ByteArray = require('bytearray-node')
const IExternalizable = require('bytearray-node/enums/IExternalizable')

class Person extends IExternalizable {
  constructor(data) {
    super()

    this.data = data
  }

  writeExternal(ba) {
    ba.writeObject(this.data)
  }

  readExternal(ba) {
    this.data = ba.readObject()
  }
}

ByteArray.registerClassAlias('src.person', Person)

const ba = new ByteArray()

ba.writeObject(new Person({id:1}))

ba.position = 0

console.log(ba.readObject())
```

**Comment by Zaseth** [comment]
I'm still hoping to hear from you, I'm awaiting pull requests.

**Comment by Flynnn** [comment]
Hi! Sorry, school keeps me pretty busy. I will need to come back to this in a couple of weeks, if that is alright with you.

**Comment by Flynnn** [comment]
In the mean time, I have open-source the project these behaviors were preventing. Within the source are some hackish patches to your library. That project contains actual AMF3 data from an old flash game that contains IExternalizeables with recursive ReadObject calls. My modifications will be at the bottom of the codec.js script in the bonk1 directory. Maybe seeing the data in action will help clarify what I am talking about.

Several weeks from now, I will try to create some simplified examples that demonstrate the error.

https://github.com/Flynnn/node-bonkio-maps

**Comment by Zaseth** [comment]
All good, just please make pull requests with tests in the pull request comment.

**Comment by Zaseth** [comment]
Please take your time with both the issues, just send pull requests and test everything (all must pass of course).

**Comment by Zaseth** [comment]
I'll be closing this issue for now. Feel free to submit pull requests anytime.
