### ISSUE TITLE
AMF3.readObject does not instantiate Externalizeable object if the traits are referenced.

### ISSUE THREAD

**Issue by Flynnn** [Zaseth/bytearray-node#7]
If AMF3.readObject encounters data that contains traits that are referencing the traits table (IE, for the second, third, fourth, so on instances of an object of identical externalizeable type), no instance of the type is ever created, and readExternal is never called.

Not sure what the best fix for this would be. I've modified my copy of this library, and for now it is working, but I have other issues clouding whether it is a total success.

**Comment by Flynnn** [comment]
I was able to mend this behavior with the following alteration to AMF3.readObject:

```js
readObject() {
    if (this.isReference('objectReferences')) {
      return this.reference
    }

    let instance = {}
    let traits;

    this.objectReferences.push(instance)

	let createReference = !this.isReference('traitReferences');

	if (createReference) {
		traits = {
			isExternallySerialized: this.popFlag(),
			isDynamicObject: this.popFlag(),
			sealedMemberCount: this.flags,
			className: this.readString(),
			sealedMemberNames: []
		}
      	this.traitReferences.push(traits)
	}
	else {
		traits = this.reference;
	}
	
	if (traits.isExternallySerialized && traits.className !== '') {
        instance = new (this.byteArr.aliasMapping[traits.className])()

        if (instance.readExternal.length !== 1) {
          throw new Error(`Expecting only 1 argument for readExternal in registered class: '${traits.className}'`)
        }

        instance.readExternal(this.byteArr)
    }

	if (createReference) {
      for (let i = 0; i < traits.sealedMemberCount; i++) {
        traits.sealedMemberNames[i] = this.readString()
      }
    }
    
    for (let i = 0; i < traits.sealedMemberCount; i++) {
      instance[traits.sealedMemberNames[i]] = this.read()
    }

    if (traits.isDynamicObject) {
      for (let key = this.readString(); key !== ''; instance[key] = this.read(), key = this.readString()) { }
    }    

    if (!traits.isExternallySerialized && !traits.isDynamicObject && traits.className !== '') {
      const classObject = new (this.byteArr.aliasMapping[traits.className])()
      const values = Object.values(instance)
      

      for (let i = 0; i < traits.sealedMemberCount; i++) {
        classObject[traits.sealedMemberNames[i]] = values[i]
      }

		console.log(classObject);
      return classObject
    }
    

    return instance
  }
```
If you think this is a sane alteration to make, @Zaseth , then I will make a branch and a pull request.

**Comment by Zaseth** [comment]
I'm not quite sure if I understand the issue. Feel free to create pull requests and test everything, I'll inspect it.

**Comment by Flynnn** [comment]
Sure thing, when I have some more time I will put something together.

**Comment by Zaseth** [comment]
I read it all again. The Externalizable class will call everything. Every object has traits, even standard objects. I'm guessing you're doing something wrong, but I don't know what.

**Comment by Zaseth** [comment]
I'm still hoping to hear from you. Please provide tests, I'm not aware of any issues so I'd like to hear from you.

**Comment by Zaseth** [comment]
I just tried your code, didn't work for me.

**Comment by Zaseth** [comment]
I'll be closing this issue for now. Feel free to submit pull requests anytime.
