### ISSUE TITLE
AMF3.ReadObject throws obscure TypeError if IExternalizable or Sealed type reference not in the aliasMapping, or if certain non-Buffer types are used to construct the ByteArray.

### ISSUE THREAD

**Issue by Flynnn** [Zaseth/bytearray-node#8]
For instance, here is one such thrown error:

> TypeError: this.byteArr.aliasMapping[traits.className] is not a constructor

It would be better to check for this and throw a human-readable error, esp. one indicating the reference not being found.

This exact error will also be thrown if a non-Buffer, but Buffer-like object (such as an ArrayBuffer) is supplied instead of a Buffer to the ByteArray constructor. I suggest doing some form of typechecking on the constructor to ensure a Buffer is supplied and strange errors are not thrown.

**Comment by Zaseth** [comment]
I've chosen not to do type check as the errors are already performed.

**Comment by Flynnn** [comment]
Are you sure? The errors do not do much to elucidate problems. in my opinion. Would you be open to a pull request implementing this?
