### ISSUE TITLE
How to parse a received amf data

### ISSUE THREAD

**Issue by Yang-z** [Zaseth/bytearray-node#9]
Hi,
In my case, an amf data is catched from http request post data or respond body.
It is a vaild amf data, and can be handled in form of Buffer or String.

So, how can I use this lib to parse this amf data?

**Comment by Zaseth** [comment]
You can pass the buffer into the ByteArray constructor:

```js
new ByteArray(Buffer.from([1,2,3]))
```

**Comment by Yang-z** [comment]
> You can pass the buffer into the ByteArray constructor:
> 
> ```js
> new ByteArray(Buffer.from([1,2,3]))
> ```
> 
> This is also noted in the API [here](https://github.com/Zaseth/bytearray-node/wiki/ByteArray).

That's actually what I tried, but it doesn't give me a "parsed" result, like it contains an object, the object has a property with a name and value.
No, I can't get the information above. 
Yes, I did check the API, but failed to find a way to get the parsed information.

**Comment by Zaseth** [comment]
Did you try `readObject`?

**Comment by Yang-z** [comment]
> Did you try `readObject`?
> 
> ```js
> const ba = new ByteArray(buffer) // AMF buffer data
> console.log(ba.readObject())
> ```

Yes, but the result is `undefined`.

By the way, there is python lib called `pyamf` which can parse the AMF data correctly.
```py
from pyamf import remoting as pyamf_remoting
decoded = pyamf_remoting.decode(content)  # ✔️
```
I just wonder if that could be possible in the js lib.

**Comment by Zaseth** [comment]
In that case, you're not converting the incoming data to a buffer correctly. How are you doing that? Please provide code.

**Comment by Zaseth** [comment]
Oh I see, you're deserializing AMF messages. My library does not support this, as it's a **ByteArray** implementation, not a **NetConnection** implementation. I'll close this issue as it's not related to the library, nor to the actual AS3 implementation. You're better off implementing the `readMessage` function yourself using my AMF implementation.
